stages:
    - build
    - deploy
  
# PAYMENTS-TEST (TODO: move to gitlab env secrets)
variables:
  RANCHER_URL: "https://rancher-dev.code.nekotal.tech/v1/"
  RANCHER_ACCESS_KEY: "A19FA7CB8DEE8D8136B9"
  RANCHER_SECRET_KEY: "Ti42AbFhYm6kgoqj1i6C3ATeHVNyUxAN2RosjrLQ"
  RANCHER_DEV_ENV: "1a42636"
  SERVER_OUTLINE: "hz-dev-2"
  
  
build-rpc:
  stage: build
  image: docker:latest
  variables:
    DOCKERFILE_NAME: Dockerfile
    JOB_NAME: $CI_JOB_NAME
    COMMIT_SHA: $CI_COMMIT_SHA
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -f $DOCKERFILE_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    # only:
    #   refs:
    #     - master
    #     - qa
    #     - dev
  
deploy-test:
  stage: deploy
  when: manual
  variables:
    STACK: rpc-etc-mainnet
    COMPOSE_FILE: docker-compose.ci.yaml
  image: registry.gitlab.nekotal.tech/base/rancher-cli:latest
  script:
    - |
      rancher up -s $STACK -d --prune -p -u
      if [ $? -ne 0 ]; then
        rancher up -s $STACK -d -r
        exit 1
      else
        rancher up -s $STACK -d -c
      fi
  only:
    refs:
      - master
