---

- name: Copy binary
  copy:
    src: "{{CUSPCLI_BINARY}}"
    dest: /usr/bin/libocli
    mode: 0755
  notify: restart libocli

- name: Copy service
  template:
    src: libocli.service.j2
    dest: /etc/systemd/system/libocli.service
  notify: systemctl

